DROP TABLE diagnostico CASCADE CONSTRAINTS;

DROP TABLE diagnostico_ge CASCADE CONSTRAINTS;

DROP TABLE empleado CASCADE CONSTRAINTS;

DROP TABLE evaluacion CASCADE CONSTRAINTS;

DROP TABLE genero CASCADE CONSTRAINTS;

DROP TABLE lista_tratamiento CASCADE CONSTRAINTS;

DROP TABLE paciente CASCADE CONSTRAINTS;

DROP TABLE profesion CASCADE CONSTRAINTS;

DROP TABLE sintoma CASCADE CONSTRAINTS;

DROP TABLE tratamiento CASCADE CONSTRAINTS;

drop table Big_Smoke_Data_Temp;

CREATE TABLE  Big_Smoke_Data_Temp (
    NOMBRE_EMPLEADO VARCHAR(200) null,
    APELLIDO_EMPLEADO VARCHAR(200) null,
    DIRECCION_EMPLEADO VARCHAR(200) null,
    TELEFONO_EMPLEADO VARCHAR(200) null,
    GENERO_EMPLEADO VARCHAR(50) null,
    FECHA_NACIMIENTO_EMPLEADO TIMESTAMP null,
    TITULO_DEL_EMPLEADO VARCHAR(200) null,
    NOMBRE_PACIENTE VARCHAR(200) null,
    APELLIDO_PACIENTE VARCHAR(200) null,
    DIRECCION_PACIENTE VARCHAR(200) null,
    TELEFONO_PACIENTE VARCHAR(200) null,
    GENERO_PACIENTE VARCHAR(50) null,
    FECHA_NACIMIENTO_PACIENTE TIMESTAMP null,
    ALTURA NUMBER null,
    PESO NUMBER null,
    FECHA_EVALUACION TIMESTAMP null,
    SINTOMA_DEL_PACIENTE VARCHAR(200) null,
    DIAGNOSTICO_DEL_SINTOMA VARCHAR(200) null,
    RANGO_DEL_DIAGNOSTICO NUMBER null,
    FECHA_TRATAMIENTO TIMESTAMP null,
    TRATAMIENTO_APLICADO VARCHAR(200)null
);

CREATE TABLE diagnostico (
    id_diagnostico NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_diag VARCHAR(50) NULL
);

CREATE TABLE diagnostico_ge (
    id_diagnostico_ge NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    rango NUMBER NOT NULL,
    sintoma NUMBER NOT NULL,
    diagnostico NUMBER NOT NULL,
    evaluacion NUMBER NOT NULL
);

CREATE TABLE empleado (
    id_empleado NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_em VARCHAR(30) NOT NULL,
    apellidos_em VARCHAR(30) NOT NULL,
    direccion_em VARCHAR(50) NOT NULL,
    telefono_em  VARCHAR(15),
    fecha_nac_em DATE NOT NULL,
    profesion NUMBER NOT NULL,
    genero NUMBER NOT NULL

);


CREATE TABLE evaluacion (
    id_evaluacion NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    empleado NUMBER NOT NULL,
    paciente NUMBER NOT NULL,
    fecha_ev DATE NOT NULL 
);


CREATE TABLE genero (
    id_genero NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_ge  CHAR NULL
);


CREATE TABLE lista_tratamiento (
    id_lista NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    paciente NUMBER NOT NULL,
    tratamiento NUMBER null,
    fecha_trat date null
);

CREATE TABLE paciente (
    id_paciente NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_pa VARCHAR(30) NOT NULL,
    apellidos_pa VARCHAR(30) NOT NULL,
    direccion_pa VARCHAR(50) NOT NULL,
    telefono_pa VARCHAR(20),
    fecha_nac_pa DATE NOT NULL,
    altura NUMBER NOT NULL,
    peso NUMBER NOT NULL,
    genero NUMBER NOT NULL
);


CREATE TABLE profesion (
    id_profesion NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_profesion VARCHAR(50) NULL
);


CREATE TABLE sintoma (
    id_sintoma     NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_sintoma VARCHAR(50)  NULL
);


CREATE TABLE tratamiento (
    id_trat    NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nombre_tra VARCHAR(50) NULL
);



ALTER TABLE diagnostico_ge
    ADD CONSTRAINT diag_ge_ev_fk FOREIGN KEY (evaluacion)
        REFERENCES evaluacion (id_evaluacion);

ALTER TABLE diagnostico_ge
    ADD CONSTRAINT diag_ge_diag_fk FOREIGN KEY (diagnostico)
        REFERENCES diagnostico (id_diagnostico);

ALTER TABLE diagnostico_ge
    ADD CONSTRAINT diag_ge_sint_fk FOREIGN KEY (sintoma)
        REFERENCES sintoma (id_sintoma);

ALTER TABLE empleado
    ADD CONSTRAINT empleado_profesion_fk FOREIGN KEY (profesion)
        REFERENCES profesion (id_profesion);

ALTER TABLE empleado
    ADD CONSTRAINT empleado_genero_fk FOREIGN KEY (genero)
        REFERENCES genero (id_genero);



ALTER TABLE evaluacion
    ADD CONSTRAINT ev_empleado_fk FOREIGN KEY (empleado)
        REFERENCES empleado (id_empleado);

ALTER TABLE evaluacion
    ADD CONSTRAINT ev_paciente_fk FOREIGN KEY (paciente)
        REFERENCES paciente (id_paciente);

ALTER TABLE lista_tratamiento
    ADD CONSTRAINT lista_tra_paciente_fk FOREIGN KEY (paciente)
        REFERENCES paciente (id_paciente);

ALTER TABLE lista_tratamiento
    ADD CONSTRAINT lista_trat_trat_fk FOREIGN KEY (tratamiento)
        REFERENCES tratamiento (id_trat);

ALTER TABLE paciente
    ADD CONSTRAINT paciente_genero_fk FOREIGN KEY (genero)
        REFERENCES genero (id_genero);
